# Generated by Django 4.2.7 on 2023-12-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='remaining_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='amount_paid',
            field=models.FloatField(),
        ),
    ]
