# Generated by Django 4.2.7 on 2023-12-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_loanrecord_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrecord',
            name='loan_balance',
            field=models.FloatField(default=0),
        ),
    ]
