# Generated by Django 4.2.7 on 2023-12-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_loanrecord_loan_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrecord',
            name='loan_balance',
            field=models.FloatField(),
        ),
    ]
