# Generated by Django 4.2.7 on 2023-12-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_loanrecord_loan_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanRecord',
            new_name='RepaymentRecord',
        ),
    ]
